
[env_common]
# use the fork that supports the ESP32-C6
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+ ; be thorough in determining what libraries are needed
; include all the libraries we might need. The linker will eliminate what is not used
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5
    olikraus/U8g2 @ ^2.36.2
    h2zero/NimBLE-Arduino @ ^1.4.1

build_flags =
    -I"${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src"
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -Wl,--allow-multiple-definition
    ; -D CORE_DEBUG_LEVEL=0           ; Set verbose debug logging level (0-5)


# ==========================================
# Shared Target Variants
# ==========================================

[base_s3_zero]
extends = env_common
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = default.csv
board_build.usb_mode = usb-device
board_build.usb_cdc = enabled
board_build.arduino.memory_type = qio_qspi
build_flags =
    ${env_common.build_flags}
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    -D BOARD_S3_ZERO
    -D HAS_NEOPIXEL
    -D STATUS_LED=21
    -D NEOPIXEL_COLOR_ORDER=NEO_RGB


[base_s3_super_mini]
extends = env_common
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = default.csv
board_build.usb_mode = usb-device
board_build.usb_cdc = enabled
board_build.arduino.memory_type = qio_qspi
build_flags =
    ${env_common.build_flags}
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    -D BOARD_S3_SUPER_MINI
    -D HAS_NEOPIXEL
    -D STATUS_LED=48
    -D NEOPIXEL_COLOR_ORDER=NEO_GRB


[base_s3_cyd_touch_freenove]
extends = env_common
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.usb_mode = usb-device
board_build.usb_cdc = enabled
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env_common.build_flags}
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    -D BOARD_S3_CYD_TOUCH_FREENOVE
    -D HAS_NEOPIXEL
    -D STATUS_LED=42


[base_c3_super_mini]
extends = env_common
board = esp32-c3-devkitm-1
build_flags =
    ${env_common.build_flags}
    -D BOARD_C3_SUPER_MINI
    -D HAS_LED
    -D STATUS_LED=8
    -D LED_ACTIVE_LOW=1


[base_c3_xiao]
extends = env_common
board = seeed_xiao_esp32c3
build_flags =
    ${env_common.build_flags}
    -D BOARD_C3_XIAO
    -D HAS_LED
    -D STATUS_LED=10


[base_c6_xiao]
extends = env_common
board = esp32-c6-devkitc-1
board_build.mcu        = esp32c6
board_build.f_cpu      = 160000000L
board_build.flash_size = 8MB
board_build.flash_mode = qio
board_upload.flash_size = 8MB
build_flags =
    ${env_common.build_flags}
    -D BOARD_C6_XIAO
    -D HAS_LED
    -D STATUS_LED=15
    -D LED_ACTIVE_LOW=1


[base_c6_super_mini]
extends = env_common
board = esp32-c6-devkitc-1
board_build.mcu        = esp32c6
board_build.f_cpu      = 160000000L
board_build.flash_size = 4MB
board_build.flash_mode = qio
board_upload.flash_size = 4MB
build_flags =
    ${env_common.build_flags}
    -D ARDUINO_USB_MSC_ON_BOOT=0
    -D BOARD_C6_SUPER_MINI
    -D HAS_NEOPIXEL
    -D STATUS_LED=15
    -D NEOPIXEL_COLOR_ORDER=NEO_RGB
