
[platformio]
src_dir = .
extra_configs = ../base_boards.ini


[env:oled-display-esp32-s3-zero]
extends = base_s3_zero

[env:oled-display-esp32-s3-super-mini]
extends = base_s3_super_mini

[env:oled-display-esp32-s3-cyd-touch-freenove]
extends = base_s3_cyd_touch_freenove

[env:oled-display-esp32-c3]
extends = base_c3_super_mini

[env:oled-display-esp32-c3-xiao]
extends = base_c3_xiao

[env:oled-display-esp32-c6-xiao]
extends = base_c6_xiao

[env:oled-display-esp32-c6]
extends = base_c6_super_mini
