
[platformio]
src_dir = .
extra_configs = ../base-boards.ini

# ------------------------------------------------------------------------------
# Central Repository Release Metadata (Non-Building Configuration Block)
# ------------------------------------------------------------------------------
[env:version_metadata]
release_version = 0.1.0


[env:cerberus-esp32-s3-cyd-touch-freenove]
extends = base_s3_cyd_touch_freenove, feature_lovyangfx
lib_deps =
    ${base_s3_cyd_touch_freenove.lib_deps}
    ${feature_lovyangfx.lib_deps}
build_flags =
    ${base_s3_cyd_touch_freenove.build_flags}
    ${feature_lovyangfx.build_flags}

[env:cerberus-m5-core]
extends = base_m5_core, feature_lovyangfx
lib_deps =
    ${base_m5_core.lib_deps}
    ${feature_lovyangfx.lib_deps}
build_flags =
    ${base_m5_core.build_flags}
    ${feature_lovyangfx.build_flags}
