
[platformio]
src_dir = .
extra_configs = ../base-boards.ini


[env:cerberus-esp32-s3-zero]
extends = base_s3_zero

[env:cerberus-esp32-s3-super-mini]
extends = base_s3_super_mini

[env:cerberus-esp32-s3-cyd-touch-freenove]
extends = base_s3_cyd_touch_freenove
lib_deps =
    ${base_s3_cyd_touch_freenove.lib_deps}
    lovyan03/LovyanGFX @ ^1.1.16
build_flags =
    ${base_s3_cyd_touch_freenove.build_flags}
    -D FNK0104AB_2P8_240x320_ILI9341
    -D ARDUINO_ARCH_ESP32=1
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=14
    -D TFT_RST=1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT7=1
    -D TFT_INVERSION_ON=1

[env:cerberus-esp32-c3]
extends = base_c3_super_mini

[env:cerberus-esp32-c3-xiao]
extends = base_c3_xiao

[env:cerberus-esp32-c6-xiao]
extends = base_c6_xiao

[env:cerberus-esp32-c6]
extends = base_c6_super_mini

[env:cerberus-m5-core]
extends = base_m5_core2
lib_deps =
    ${base_m5_core2.lib_deps}
    lovyan03/LovyanGFX @ ^1.1.16
build_flags =
    ${base_m5_core2.build_flags}
    
    
